name: 'Check code quality'
description: 'Checks code quality: prettier, linters, build and test'
runs:
  using: 'composite'
  steps:
    - shell: bash
      name: Lint
      run: pnpm lint

    - shell: bash
      name: Tests
      run: pnpm test
