name: Check code quality

env:
  APP_CI: true
  APP_ENV: development
  NODE_VERSION: 22.14.0
  PNPM_VERSION: 10.7.0

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: qualityCheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qualityCheck:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup project'
        uses: ./.github/actions/setup-project
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Check code quality'
        uses: ./.github/actions/quality-check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build project'
        run: pnpm build
